apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: partner-partner-steward-2-auth-job
  annotations:
    fluxcd.io/automated: "false"
  namespace: partner-ns
spec:
  releaseName: partner-partner-steward-2-auth-job
  chart:
    path: platforms/hyperledger-indy/charts/indy-auth-job
    git: https://github.com/savydevsoft/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      name: partner-partner-steward-2-auth-job
      namespace: partner-ns
    network:
      name: indy
      kubernetes_url: https://6D8F63EACC5CFD77B375F109AA39B373.gr7.us-east-2.eks.amazonaws.com
    image:
      name: partner
      repository: alpine:3.9.4
    vault:
      address: http://a33d597269aea474aa5475dc4f7cbda4-205388225.us-east-2.elb.amazonaws.com:8200
      keyPath: partner.stewards
      identity: partner-steward-2
      admin_auth_path: kubernetes-partner-admin-auth
      policy: partner-partner-steward-2-ro
      policy_content: path \"/partner/stewards/partner-steward-2/*\" { capabilities = [ \"read\", \"list\" ] }
      auth_path: kubernetes-partner-partner-steward-2-auth
    account:
      admin_service: partner-admin-vault-auth
      admin_role: rw
      service: partner-partner-steward-2-vault-auth
      role: ro
