apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: crowdkeep-crowdkeep-endorser-auth-job
  annotations:
    fluxcd.io/automated: "false"
  namespace: crowdkeep-ns
spec:
  releaseName: crowdkeep-crowdkeep-endorser-auth-job
  chart:
    path: platforms/hyperledger-indy/charts/indy-auth-job
    git: https://github.com/savydevsoft/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      name: crowdkeep-crowdkeep-endorser-auth-job
      namespace: crowdkeep-ns
    network:
      name: indy
      kubernetes_url: https://6D8F63EACC5CFD77B375F109AA39B373.gr7.us-east-2.eks.amazonaws.com
    image:
      name: crowdkeep
      repository: alpine:3.9.4
    vault:
      address: http://a33d597269aea474aa5475dc4f7cbda4-205388225.us-east-2.elb.amazonaws.com:8200
      keyPath: crowdkeep.endorsers
      identity: crowdkeep-endorser
      admin_auth_path: kubernetes-crowdkeep-admin-auth
      policy: crowdkeep-crowdkeep-endorser-ro
      policy_content: path \"/crowdkeep/endorsers/crowdkeep-endorser/*\" { capabilities = [ \"read\", \"list\" ] }
      auth_path: kubernetes-crowdkeep-crowdkeep-endorser-auth
    account:
      admin_service: crowdkeep-admin-vault-auth
      admin_role: rw
      service: crowdkeep-crowdkeep-endorser-vault-auth
      role: ro
