apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: crowdkeep-crowdkeep-steward-1
  annotations:
    fluxcd.io/automated: "false"
  namespace: crowdkeep-ns
spec:
  releaseName: crowdkeep-crowdkeep-steward-1
  chart:
    path: platforms/hyperledger-indy/charts/indy-key-mgmt
    git: https://github.com/savydevsoft/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      name: crowdkeep-crowdkeep-steward-1
      namespace: crowdkeep-ns
    network:
      name: indy
    image:
      name: crowdkeep
      repository: index.docker.io/hyperledgerlabs/indy-key-mgmt:1.11.0
      pullSecret: regcred
    vault:
      address: http://a33d597269aea474aa5475dc4f7cbda4-205388225.us-east-2.elb.amazonaws.com:8200
      keyPath: crowdkeep.stewards
      identity: crowdkeep-steward-1
      auth_path: kubernetes-crowdkeep-admin-auth
    account:
      service: crowdkeep-admin-vault-auth
      role: rw
