apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: crowdkeep-crowdkeep-steward-2-vault-auth-role-binding
  namespace: crowdkeep-ns
  labels:
    organization: crowdkeep
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: crowdkeep-crowdkeep-steward-2-vault-auth
  namespace: crowdkeep-ns
