apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: softtik-softtik-trustee-auth-job
  annotations:
    fluxcd.io/automated: "false"
  namespace: softtik-ns
spec:
  releaseName: softtik-softtik-trustee-auth-job
  chart:
    path: platforms/hyperledger-indy/charts/indy-auth-job
    git: https://github.com/savydevsoft/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      name: softtik-softtik-trustee-auth-job
      namespace: softtik-ns
    network:
      name: indy
      kubernetes_url: https://6D8F63EACC5CFD77B375F109AA39B373.gr7.us-east-2.eks.amazonaws.com
    image:
      name: softtik
      repository: alpine:3.9.4
    vault:
      address: http://a33d597269aea474aa5475dc4f7cbda4-205388225.us-east-2.elb.amazonaws.com:8200
      keyPath: softtik.trustees
      identity: softtik-trustee
      admin_auth_path: kubernetes-softtik-admin-auth
      policy: softtik-softtik-trustee-ro
      policy_content: path \"/softtik/trustees/softtik-trustee/*\" { capabilities = [ \"read\", \"list\" ] }
      auth_path: kubernetes-softtik-softtik-trustee-auth
    account:
      admin_service: softtik-admin-vault-auth
      admin_role: rw
      service: softtik-softtik-trustee-vault-auth
      role: ro
