apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: crowdkeep-crowdkeep-steward-1-node
  annotations:
    fluxcd.io/automated: "false"
  namespace: crowdkeep-ns
spec:
  releaseName: crowdkeep-crowdkeep-steward-1-node
  chart:
    path: platforms/hyperledger-indy/charts/indy-node
    git: https://github.com/savydevsoft/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      name: crowdkeep-crowdkeep-steward-1-node
      namespace: crowdkeep-ns
    network:
      name: indy
    organization:
      name: crowdkeep
    genesis:
      add_org: False
    image:
      pullSecret: regcred
      initContainer:
        name: crowdkeep-crowdkeep-steward-1-node-init
        repository: alpine:3.9.4
      cli:
        name: crowdkeep-crowdkeep-steward-1-node-ledger-txn
        repository: index.docker.io/hyperledgerlabs/indy-ledger-txn:latest
        pullSecret: regcred  
      indyNode:
        name: crowdkeep-crowdkeep-steward-1-node
        repository: index.docker.io/hyperledgerlabs/indy-node:1.11.0
    node:
      name: crowdkeep-steward-1
      ip: 0.0.0.0
      publicIp: 18.189.128.201
      port: 9711
      ambassadorPort: 9711
    client:
      publicIp: 18.189.128.201
      ip: 0.0.0.0
      port: 9712
      ambassadorPort: 9712
    service:
      type: ClusterIP
      ports:
        nodePort: 9711
        nodeTargetPort: 9711
        clientPort: 9712
        clientTargetPort: 9712
    configmap:
      indyConfig: |-
        NETWORK_NAME = 'indy'
        # Enable stdout logging
        enableStdOutLogging = True
        logRotationBackupCount = 10
        # Directory to store ledger.
        LEDGER_DIR = '/var/lib/indy/data'
        # Directory to store logs.
        LOG_DIR = '/var/log/indy'
        # Directory to store keys.
        KEYS_DIR = '/var/lib/indy/keys'
        # Directory to store genesis transactions files.
        GENESIS_DIR = '/var/lib/indy/genesis'
        # Directory to store backups.
        BACKUP_DIR = '/var/lib/indy/backup'
        # Directory to store plugins.
        PLUGINS_DIR = '/var/lib/indy/plugins'
        # Directory to store node info.
        NODE_INFO_DIR = '/var/lib/indy/data'
    ambassador:
      annotations: |-
        ---
        apiVersion: ambassador/v2
        kind: TCPMapping
        name: crowdkeep-crowdkeep-steward-1-node-node-mapping
        port: 9711
        service: crowdkeep-crowdkeep-steward-1-node.crowdkeep-ns:9711
        ---
        apiVersion: ambassador/v2
        kind: TCPMapping
        name: crowdkeep-crowdkeep-steward-1-node-client-mapping
        port: 9712
        service: crowdkeep-crowdkeep-steward-1-node.crowdkeep-ns:9712
    vault:
      address: http://a33d597269aea474aa5475dc4f7cbda4-205388225.us-east-2.elb.amazonaws.com:8200
      serviceAccountName: crowdkeep-crowdkeep-steward-1-vault-auth
      keyPath: /keys/indy/keys/crowdkeep-steward-1
      authPath: kubernetes-crowdkeep-crowdkeep-steward-1-auth
      nodeId: crowdkeep-steward-1
      role: ro
    storage:
      data:
        storagesize: 3Gi
        storageClassName: crowdkeep-aws-storageclass
      keys:
        storagesize: 3Gi
        storageClassName: crowdkeep-aws-storageclass
