apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: softtik-softtik-trustee
  annotations:
    fluxcd.io/automated: "false"
  namespace: softtik-ns
spec:
  releaseName: softtik-softtik-trustee
  chart:
    path: platforms/hyperledger-indy/charts/indy-key-mgmt
    git: https://github.com/savydevsoft/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      name: softtik-softtik-trustee
      namespace: softtik-ns
    network:
      name: softtik
    image:
      name: softtik
      repository: index.docker.io/hyperledgerlabs/indy-key-mgmt:1.11.0
      pullSecret: regcred
    vault:
      address: http://a33d597269aea474aa5475dc4f7cbda4-205388225.us-east-2.elb.amazonaws.com:8200
      keyPath: softtik.trustees
      identity: softtik-trustee
      auth_path: kubernetes-softtik-admin-auth
    account:
      service: softtik-admin-vault-auth
      role: rw
