apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: crowdkeep-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: crowdkeep-ns
spec:
  releaseName: crowdkeep-dtg
  chart:
    path: platforms/hyperledger-indy/charts/indy-domain-genesis
    git: https://github.com/savydevsoft/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      name: crowdkeep-dtg
      namespace: crowdkeep-ns
    organization:
      name: crowdkeep
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"softtik-trustee","dest":"ATyzW5JrkW1SfwzqPa47xX","role":"0","verkey":"6ADRWXckYCVbvgbM9EYyBXAcg4pgPsh1HpVkiGfaMJAu"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"crowdkeep-trustee","dest":"Mf64S8ocuGyZYD9PoRmMpx","role":"0","verkey":"CFzu9ktSopp74Pree1ni3tu9iwZGGMrEhFy8vLUPcwNP"},"metadata":{"from":"ATyzW5JrkW1SfwzqPa47xX"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"crowdkeep-steward-1","dest":"QYAtQJdn88eDW3hUTEE5hf","role":"2","verkey":"Dq4jJHxHMuCxukzRXD8b22TNwj7kLDH3C4ETZHoonBfW"},"metadata":{"from":"Mf64S8ocuGyZYD9PoRmMpx"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"crowdkeep-steward-2","dest":"7BNiR3Pu1874yoeAUkfhon","role":"2","verkey":"4NKvQ4UDdpyY25t5tod4iQ8pzFNNabvoDLWdx37J6wvg"},"metadata":{"from":"Mf64S8ocuGyZYD9PoRmMpx"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-trustee","dest":"UAmV67p45enUgQCbbCgyGC","role":"0","verkey":"For6pg2c93nwdL7CERkigtvyNEn97MzDU4KDTiGvjsJs"},"metadata":{"from":"ATyzW5JrkW1SfwzqPa47xX"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-steward-1","dest":"7V4s5teDp7kAJekC5vC669","role":"2","verkey":"4XyD1KjLk4hWmFGjAPrZK5G2RhiZoGSH37YBxia9pe1D"},"metadata":{"from":"UAmV67p45enUgQCbbCgyGC"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-steward-2","dest":"NmKmbzzS4DymEyToUYEJRE","role":"2","verkey":"Cs1YBeGKZEbcXBTyzhEgJVuotAHn7d4MrxRRh3ghXGPu"},"metadata":{"from":"UAmV67p45enUgQCbbCgyGC"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
